const PRAYERS = [
  { id:1, kind:"Traditional mantra", name:"Guru Brahma", when:"Before class or thanking a teacher",
    say:"Guru Brahma guru Vishnu,\nGuru devo Maheshwara,\nGuru sakshat para Brahma,\nTasmai shree gurave namah!",
    mean:"The same God who makes, protects, and guides the world also teaches through the people who teach us. We fold our hands to that teacher-light.",
    do:"Say this before homework. Name one teacher you are grateful for.",
    kid:"A thank-you prayer for teachers." },
  { id:2, kind:"Traditional mantra", name:"Tvameva Mata", when:"Anytime you want to feel close to God",
    say:"Tvameva mata cha pita tvameva,\nTvameva bandhush cha sakha tvameva,\nTvameva vidya dravinam tvameva,\nTvameva sarvam mama deva deva!",
    mean:"God is as close as mom, dad, a sibling, and a best friend. Learning and what we need also come from that same love. God is our whole world.",
    do:"Put a hand on your heart and say the last line slowly.",
    kid:"God is family, friend, and everything." },
  { id:3, kind:"Home bhajan", name:"Saathe Ramiye", when:"Before eating",
    say:"Saathe ramiye, saathe jamiye,\nSaathe kariye saara kaam.\nKayam rehjo aapni saathe,\nGhut ghut vasta Shri Bhagvan!",
    mean:"Play, eat, and do good work as one family. We ask God, who is with every breath, to stay beside us at the table.",
    do:"Say this with folded hands before the first bite.",
    kid:"The food-grace prayer." },
  { id:4, kind:"Home bhajan", name:"Ame To Tara Nana", when:"Morning, or when you need courage",
    say:"Ame to tara nana bal,\nAmari tu leje sambhal.\nDagle dagle bhulo amari,\nDe sadbuddhi, bhulo visari.",
    mean:"We are small children in God’s care. When we stumble, we ask for a clear mind and a fresh start.",
    do:"Say the first two lines when you feel small or worried.",
    kid:"We are God’s little kids." },
  { id:5, kind:"Home bhajan", name:"Mara Prabhu To Nana", when:"When thinking of little Krishna",
    say:"Mara Prabhu to nana che,\nDuniya bhar na raja che,\nAabhe chadi ne ubha che,\nSaagar jud ma soota che.",
    mean:"Krishna can look like a child and still be Lord of everything. The song pictures him in the sky, in the sea, and playing by the river.",
    do:"Smile while you say it — it is a happy Krishna song.",
    kid:"Little Krishna is king of the world." },
  { id:6, kind:"Home bhajan", name:"Vandan Karoo", when:"Bedtime",
    say:"Vandan karoo Prabhu charanoma aaje,\nKoti pranam karoo preme re.\nJaane ajaane bhulo kidhi me,\nAakha divas ma aaje re.",
    mean:"Before sleep we bow with love. We ask pardon for today’s slips — the ones we saw and the ones we missed — and we ask for peaceful rest.",
    do:"Say this after lights are low, then take three quiet breaths.",
    kid:"The goodnight prayer." },
  { id:7, kind:"Home bhajan", name:"Vandan Kariye", when:"Morning respect to parents and God",
    say:"Vandan kariye Shree Prabhu tamne.\nPehlu vandan maat pita ne,\nBeeju vandan guruji tamne.",
    mean:"Morning starts with respect: first God, then parents, then the teacher. The rest of the song greets the Divine Mother, Shiva, and Vishnu and asks for a happy day.",
    do:"Bow to Mom or Dad after the first two lines.",
    kid:"Bow to parents, teachers, and God." },
  { id:8, kind:"Home bhajan", name:"O Ishwar Bhajiye", when:"When you want to grow good qualities",
    say:"O Ishwar bhajiye tane,\nMoto che tuj naam.\nGun tara neet gaiye,\nThay amara kaam.",
    mean:"We sing God’s great name and ask for a clean heart. The prayer is a list of good habits: forgive, share food, welcome guests, and use eyes, ears, and words kindly.",
    do:"Pick one wish — keep my heart clean — and try it all day.",
    kid:"A wish-list prayer for a kind heart." },
  { id:9, kind:"Traditional hymn", name:"Hari Om Tat Sat", when:"When you want to feel God in everyone",
    say:"Hari Om Tat Sat Shree Narayan tu,\nPurushottam guru tu.\nSiddha Buddha tu, Skand Vinayak,\nSavita pavak tu.",
    mean:"One truth, many holy names. The song points to Narayan, the teacher, Buddha, Ganesh, the sun, Ram, Krishna — all as one Lord.",
    do:"After each tu, tap your heart once.",
    kid:"One God, many holy names." },
  { id:10, kind:"Home bhajan", name:"Mandir Taaru", when:"Outside, looking at the world",
    say:"Mandir taaru vishwa rupaadu,\nSundar sarjanhara re.\nPal pal tara darshan thaye,\nDekhe dekhanhara re.",
    mean:"Creation itself is the temple — always open. Sun and moon are like aarti. If we look with love, darshan is everywhere, including inside us.",
    do:"Look out a window and name three beautiful things God made.",
    kid:"The world is God’s temple." },
  { id:11, kind:"Traditional bhajan", name:"Raghupati Raghav", when:"Anytime — a famous Ram bhajan",
    say:"Raghupati Raghav Raja Ram,\nPatita pavan Sita Ram.\nIshwar Allah tero naam,\nSabko sanmati de Bhagvan.",
    mean:"We praise Ram, who lifts people up. People may say Ishwar or Allah. The prayer asks one gift for everybody: a good mind.",
    do:"Clap the beat on Raja Ram.",
    kid:"Ram’s song — God has many names." },
  { id:12, kind:"Home bhajan", name:"Nandlala Nandlala", when:"When you want a joyful Krishna song",
    say:"Nandlala, Nandlala, Nandlala Gopala,\nKanhaiya, Kanhaiya, Kanhaiya Gopala.\nYamuna ne ghate vhalo bansi bajave,\nBansi bajave valo sau ne nachave.",
    mean:"A happy name-song for Krishna, the cowherd of Nand’s house. He plays the flute by the Yamuna and the whole village wants to dance.",
    do:"Sway a little. This one likes movement.",
    kid:"Flute-playing Krishna makes us dance." },
  { id:13, kind:"Home bhajan", name:"Mangal Mandir Kholo", when:"When you want God’s door to open",
    say:"Mangal mandir kholo,\nDayamayi mangal mandir kholo.\nJeevan van ati vege vatavyu,\nDwar ubho shishu bholo.",
    mean:"We ask the Kind One to open the door of the happy temple. Life moves fast like a forest path. A simple child is waiting outside and hopes to be held.",
    do:"Imagine knocking on a golden door, then smiling as it opens.",
    kid:"Please open your kind door." },
  { id:14, kind:"Traditional mantra", name:"Asato Ma", when:"When you want light and truth",
    say:"Asato ma sad gamaya,\nTamaso ma jyotir gamaya,\nMrityor ma amritam gamaya.",
    mean:"Walk me toward what is true, toward light, and toward the life that does not fade. Three short asks. One deep wish.",
    do:"Whisper it three times. It is short and powerful.",
    kid:"Lead me from dark to light." },
  { id:15, kind:"Home bhajan", name:"Ekaj De Chingari", when:"When you need one spark of help",
    say:"Ekaj de chingari, Mahanala,\nEkaj de chingari.\nChando salagyo, suraj salagyo,\nSalagi aabh atari.",
    mean:"Sun, moon, and sky already shine. We only ask for one small spark so our own little lamp can light up too.",
    do:"Cup your hands like a tiny flame while you say chingari.",
    kid:"Just one spark, please." },
  { id:16, kind:"Home bhajan", name:"Ram Rakhe Tem Rahiye", when:"When life feels up and down",
    say:"Ram rakhe tem rahiye, Odhavaji,\nRam rakhe tem rahiye.\nKoi din rehvane baag bagicha,\nTo koi din jungle rahiye.",
    mean:"Stay peaceful in whatever place Ram keeps you. Garden days and forest days both come. Soft bed or hard floor, feast or simple food — same calm heart.",
    do:"Use this when plans change. Shrug kindly and smile.",
    kid:"Stay how Ram keeps you." },
  { id:17, kind:"Home bhajan", name:"He Karuna Na Karnara", when:"When you want God’s kindness",
    say:"He karuna na karnara,\nTari karuna no koi paar nathi.\nHe sankat na harnara,\nTari karuna no koi paar nathi.",
    mean:"We call the One who gives mercy and lifts trouble. Kindness here has no fence. Even a forgotten mistake can fit inside that mercy.",
    do:"If you feel sorry about something, say the first two lines.",
    kid:"God’s kindness has no edge." },
  { id:18, kind:"Home bhajan", name:"Swikari Lyo", when:"When offering prayer or flowers",
    say:"Swikari lyo, swikari lyo,\nVandan aaj amara.\nAme balak chhiye tamara,\nPrabhu balak chhiye tamara.",
    mean:"Please take our bow. We are your children. If we have few flowers in the hand, we still offer the love that grew in the heart.",
    do:"Offer a real flower, or pretend one in your palm.",
    kid:"Please accept our little flowers." },
  { id:19, kind:"Traditional bhajan", name:"Choti Choti Gaiya", when:"A sweet song for baby Krishna",
    say:"Choti choti gaiya, chote chote gwaal,\nChotoso mero Madan Gopal.\nAage aage gaiya, pichhe pichhe gwaal,\nBeech mein mero Madan Gopal.",
    mean:"Tiny cows in front, tiny friends behind, and little Krishna walking in the middle. A picture-song of Vrindavan play — grass, milk, butter, flute.",
    do:"Hold up a tiny flute with two fingers.",
    kid:"Tiny cows, tiny Krishna." },
  { id:20, kind:"Traditional mantra", name:"Navkar Mantra", when:"A Jain peace mantra, any quiet moment",
    say:"Namo Arihantanam\nNamo Siddhanam\nNamo Ayariyanam\nNamo Uvajjhayanam\nNamo Loe Savva Sahunam.",
    mean:"Five bows: to the liberated, the perfected, the masters, the teachers, and every sincere seeker. The bows are a way to set the heart in a harmless direction.",
    do:"Count five bows on your fingers.",
    kid:"Five holy bows for a clean heart." },
  { id:21, kind:"Traditional bhajan", name:"Achyutam Keshavam", when:"A playful Krishna-Ram song",
    say:"Achyutam Keshavam Krishna Damodaram,\nRama Narayanam Janaki Vallabham.\nKaun kehta hai Bhagvan aate nahi?\nTum Meera ke jaise bulate nahi.",
    mean:"Many names, one Lord. The later lines tease us: God does come — we just do not call with the love of Meera, Shabri, Yashoda, or the gopis.",
    do:"Call Krishna once, the way you would call a friend.",
    kid:"Call God the way Meera did." },
  { id:22, kind:"Traditional mantra", name:"Gayatri Mantra", when:"Morning, or before studying",
    say:"Om bhur bhuvah swaha,\nTat savitur varenyam,\nBhargo devasya dhimahi,\nDhiyo yo nah prachodayat.",
    mean:"We rest the mind on the light that made the worlds, and we ask that same light to wake up our thinking.",
    do:"Sit tall. Say it three times before schoolwork.",
    kid:"Wake up my mind, bright God." }
];
